#!/usr/bin/env python3
"""
Generates docs/LIVE_CAMPAIGN.md: the ordered Studio test table with full wallet addresses in every step.

    python3 scripts/make_campaign.py W1 W2 W3 W4 W5 [REGISTRY LEDGER MARKET]

Unknown values are printed as <WALLET-n ADDRESS> / <REGISTRY ADDRESS> and so on.
"""
import os
import sys

AT = "0x9d04ea1E3C0BBA11c85e7325C87D2E009AcF3ccc"
ROLES = ["client / buyer / deployer", "agent / worker", "second bidder", "juror", "juror"]
REPO = "https://github.com/123Cryp/AgentBazaar"
RAW = "https://raw.githubusercontent.com/123Cryp/AgentBazaar/main/docs/profiles/"


def main(argv):
    w = list(argv[:5]) + [None] * (5 - len(argv[:5]))
    w = [x or "<WALLET-%d ADDRESS>" % (i + 1) for i, x in enumerate(w)]
    extra = list(argv[5:8]) + [None] * (3 - len(argv[5:8]))
    reg = extra[0] or "<REGISTRY ADDRESS>"
    led = extra[1] or "<LEDGER ADDRESS>"
    mkt = extra[2] or "<MARKET ADDRESS>"
    rows = []

    def step(wallet, target, method, args, expect, alarm=""):
        rows.append((wallet, target, method, args, expect, alarm))

    step(1, "deploy", "AgentRegistry (contracts/agent_registry.py)", "no args", "contract address -> REGISTRY", "A red (constructor) row on a deploy is a real failure")
    step(1, "deploy", "ReputationLedger (contracts/reputation_ledger.py)", "no args", "contract address -> LEDGER")
    step(1, "deploy", "JobMarket (build/job_market_short_window.py)", "no args", "contract address -> MARKET", "Use the short-window build; one hour = one minute")
    step(1, "ledger " + led, "set_wiring", '"%s", "%s"' % (AT, mkt), "returns the ledger address / wired", "Only the deployer can call; second call must fail")
    step(1, "market " + mkt, "set_wiring", '"%s", "%s", "%s"' % (AT, reg, led), "wired", "Second call must fail")
    step(1, "registry " + reg, "set_job_market", '"%s"' % mkt, "returns the market address", "Second call must fail")
    step(2, "registry " + reg, "register_agent", '"Alpha Agent", "https://github.com/<your-user>/<repo>/blob/main/PROFILE.md", "python apis, code review"', "AG-1", "The profile page MUST contain the full address of Wallet 2: " + w[1])
    step(3, "registry " + reg, "register_agent", '"Beta Agent", "<profile page containing %s>", "data cleaning"' % w[2], "AG-2")
    step(1, "registry " + reg, "verify_claims", '"AG-1"', "CLAIMS_SUPPORTED or CLAIMS_PARTIAL", "Wait for consensus; do not send reads in parallel (Studio RPC)")
    step(1, "registry " + reg, "verify_claims", '"AG-2"', "any verdict", "CLAIMS_UNSUPPORTED blocks bidding")
    step(1, "market " + mkt, "post_job", '"Add a health endpoint", "Deliver a Flask service that exposes GET /health returning 200.", 5000000000000000000, <unix time now + 600>', "JB-1", "Budget is wei; deadline is a unix timestamp at least 120 s ahead")
    step(2, "market " + mkt, "submit_bid", '"JB-1", 4000000000000000000, "I ship small Flask services with tests and a health check."', "BD-1")
    step(3, "market " + mkt, "submit_bid", '"JB-1", 3000000000000000000, "I can do this quickly."', "BD-2")
    step(1, "market " + mkt, "assess_bid", '"BD-1"', "STRONG_FIT")
    step(1, "market " + mkt, "assess_bid", '"BD-2"', "PARTIAL_FIT or POOR_FIT", "A POOR_FIT bid cannot be selected")
    step(1, "market " + mkt, "list_bids", '"JB-1"', "BD-1 ranked first")
    step(1, "market " + mkt, "select_bid", '"JB-1", "BD-1"', "AWARDED", "Wait for the 120 s bid deadline only if the contract asks; selection is allowed while OPEN")
    step(1, "AgentTrust " + AT, "create_agreement", 'title "[JB-1] Health endpoint", worker %s, currency GEN, amount 4000000000000000000, evidence kind github_file' % w[1], "AT-n", "Title must contain [JB-1]; amount must equal the winning price")
    step(1, "AgentTrust " + AT, "fund (Value field = 4 whole GEN)", '"AT-n"', "FUNDED", "The Value field takes whole GEN only. The transfer shows as a red (constructor) row; that is Studio display only")
    step(1, "market " + mkt, "link_agreement", '"JB-1", "AT-n"', "LINKED")
    step(2, "AgentTrust " + AT, "accept, start_work, submit_deliverable", '"AT-n" ... github_file evidence', "DELIVERED")
    step(4, "AgentTrust " + AT, "juror steps as in the AgentTrust guide", '"AT-n"', "jury seated", "Jury seating needs about 90 s after the challenge phase. Wallet 5 is the second juror: " + w[4])
    step(1, "AgentTrust " + AT, "aggregate / settle", '"AT-n"', "SETTLED or REFUNDED")
    step(1, "market " + mkt, "sync_agreement", '"JB-1"', "CLOSED")
    step(1, "ledger " + led, "record_outcome", '"AT-n"', "COMPLETED (or REFUNDED)")
    step(1, "ledger " + led, "get_profile", '"%s"' % w[1].lower(), "completed 1, tier ESTABLISHED or EMERGING")
    step(1, "ledger " + led, "record_outcome", '"AT-1"', "an outcome kind or a clear rejection", "Leftover AgentTrust agreement; a rejection message is a valid result")

    out = ["# Live Studio campaign", "", "Generated by `scripts/make_campaign.py`. Run one step at a time and wait for the transaction to finish. Never send parallel reads.", "",
           "| Wallet | Role | Full address |", "|---|---|---|"]
    for i in range(5):
        out.append("| Wallet %d | %s | `%s` |" % (i + 1, ROLES[i], w[i]))
    out += ["", "AgentTrust test build: `%s` (WINDOW_UNIT = 60)." % AT, "",
            "| # | Wallet and address | Target | Method | Arguments | Expected | Alarms |", "|---|---|---|---|---|---|---|"]
    for n, (wl, target, method, args, expect, alarm) in enumerate(rows, 1):
        out.append("| %d | Wallet %d `%s` | %s | %s | %s | %s | %s |" % (n, wl, w[wl - 1], target, method, args.replace("|", "/"), expect, alarm))
    out.append("")
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "docs", "LIVE_CAMPAIGN.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print("wrote", os.path.normpath(path), "with", len(rows), "steps")


if __name__ == "__main__":
    main(sys.argv[1:])
